// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFhqPreq7Qy4QMz-DlyEDfmm8ia45ebag',
    appId: '1:547857919415:web:8efeb6f9232abd5e254c32',
    messagingSenderId: '547857919415',
    projectId: 'babyshophub-914fa',
    authDomain: 'babyshophub-914fa.firebaseapp.com',
    storageBucket: 'babyshophub-914fa.appspot.com',
    measurementId: 'G-6G8D5LGRQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB84g5dFQ9m_9mX6c9Nb9tUBr8KwUdZw4o',
    appId: '1:547857919415:android:65a6d6dcd6642437254c32',
    messagingSenderId: '547857919415',
    projectId: 'babyshophub-914fa',
    storageBucket: 'babyshophub-914fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD50tbMerzrdlT1wRNz4RRhNNJ0RoKdppg',
    appId: '1:547857919415:ios:598be19bbad59f13254c32',
    messagingSenderId: '547857919415',
    projectId: 'babyshophub-914fa',
    storageBucket: 'babyshophub-914fa.appspot.com',
    iosBundleId: 'com.example.babyshophub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD50tbMerzrdlT1wRNz4RRhNNJ0RoKdppg',
    appId: '1:547857919415:ios:cc585ecbbec03f3f254c32',
    messagingSenderId: '547857919415',
    projectId: 'babyshophub-914fa',
    storageBucket: 'babyshophub-914fa.appspot.com',
    iosBundleId: 'com.example.furnitureShopTeamwork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFhqPreq7Qy4QMz-DlyEDfmm8ia45ebag',
    appId: '1:547857919415:web:8efeb6f9232abd5e254c32',
    messagingSenderId: '547857919415',
    projectId: 'babyshophub-914fa',
    authDomain: 'babyshophub-914fa.firebaseapp.com',
    storageBucket: 'babyshophub-914fa.appspot.com',
    measurementId: 'G-6G8D5LGRQ0',
  );

}